
function showGuide(response) {
  new Typewriter("#guide", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}

function generateGuide(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "f92fe2190a73t0c3474809d37ba10o1b";

  let context =
  "You are a friendly geography teacher in a learning app. Generate one short Factual and educational paragraph about the requested country using ONLY basic HTML. provide interesting and educational facts that help students learn more about the country. Do NOT use markdown. Do NOT include a title. At the end, provide a safe and reliable external link (such as Britannica or Wikipedia) for further learning. Finish with Generated by: <strong>SheCodes AI</strong>.";
  let prompt = `Please provide information about ${instructionsInput.value}`;

  let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${encodeURIComponent(
    prompt
  )}&context=${encodeURIComponent(context)}&key=${apiKey}`;

  let guideElement = document.querySelector("#guide");
  guideElement.classList.remove("hidden");
  guideElement.innerHTML = `⏳ Generating a tour plan for ${instructionsInput.value}...`;

  axios.get(apiURL).then(showGuide);
}

let guideFormElement = document.querySelector("#guide-generator-form");
guideFormElement.addEventListener("submit", generateGuide);